# Generated by Django 3.2.9 on 2021-12-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
